include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-online-devices
PKG_RELEASE:=1
PKG_LICENSE:=MIT
PKG_MAINTAINER:=XXNplc

include $(TOPDIR)/feeds/luci/luci.mk

LUCI_TITLE:=LuCI Online Devices
LUCI_DEPENDS:=+luci-base +rpcd +ucode

# call BuildPackage - OpenWrt buildroot signature
