include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-online-devices
PKG_VERSION:=0.1.0
PKG_RELEASE:=1

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=XXNplc

include $(TOPDIR)/feeds/luci/luci.mk

LUCI_TITLE:=在线设备
LUCI_PKGARCH:=all

# call BuildPackage
